inherit_from: .rubocop_todo.yml
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Style/Documentation:
  Exclude:
    - 'app/services/**/*'

Metrics/AbcSize:
  Exclude:
      - 'app/services/**/*'